# Generated by Django 2.0.4 on 2018-04-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_addr',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('hostname', 'ip_addr')},
        ),
    ]
