# Generated by Django 2.0.4 on 2018-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20180417_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
