# Generated by Django 2.0.4 on 2018-04-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180418_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
